# Generated by Django 3.2 on 2021-07-29 21:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profpic', cloudinary.models.CloudinaryField(blank=True, default='image', max_length=255, verbose_name='profile_pics/')),
                ('description', tinymce.models.HTMLField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.locations')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('notification', tinymce.models.HTMLField()),
                ('priority', models.CharField(choices=[('All farmers', 'All farmers')], default='CEO', max_length=15)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('by', models.CharField(default='Manager', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField()),
                ('name', models.CharField(max_length=100)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Dailyrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('litres', models.IntegerField(default=0)),
                ('weeekdays', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Informational', max_length=15)),
                ('serveBy', models.CharField(choices=[('Dennis', 'Dennis'), ('Jalody', 'Jalody'), ('Melby', 'Melby'), ('Juma Allan', 'Juma Allan')], default='Informational', max_length=15)),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairyapp.locations')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
