# Generated by Django 3.2 on 2021-07-29 21:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='post_date',
        ),
        migrations.AddField(
            model_name='dailyrecords',
            name='weeekdays',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Informational', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profpic',
            field=cloudinary.models.CloudinaryField(blank=True, default='image', max_length=255, verbose_name='profile_pics/'),
        ),
    ]
