# Generated by Django 3.2 on 2021-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_auto_20210730_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecords',
            name='service',
            field=models.CharField(choices=[('Dennis', 'Dennis'), ('Jalody', 'Jalody'), ('Melby', 'Melby'), ('Juma Allan', 'Juma Allan')], default='Informational', max_length=15),
        ),
    ]
