# Generated by Django 3.2 on 2021-07-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='email',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='priority',
            field=models.CharField(choices=[('All farmers', 'All farmers')], default='Informational', max_length=15),
        ),
    ]
