# Generated by Django 3.2 on 2021-07-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0003_dailyrecords_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecords',
            old_name='service',
            new_name='serveBy',
        ),
    ]
