# Generated by Django 3.2 on 2021-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0004_rename_service_dailyrecords_serveby'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='by',
            field=models.CharField(choices=[('Dennis', 'Dennis'), ('Jalody', 'Jalody'), ('Melby', 'Melby'), ('Juma Allan', 'Juma Allan')], default='CEO', max_length=15),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='priority',
            field=models.CharField(choices=[('All farmers', 'All farmers')], default='CEO', max_length=15),
        ),
    ]
