# Generated by Django 3.2 on 2021-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0005_auto_20210730_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='by',
            field=models.CharField(choices=[('Dennis', 'Dennis'), ('Jalody', 'Jalody'), ('Melby', 'Melby'), ('Juma Allan', 'Juma Allan')], default='Manager', max_length=15),
        ),
    ]
