# Generated by Django 3.2 on 2021-07-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairyapp', '0006_alter_notifications_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='by',
            field=models.CharField(default='Manager', max_length=15),
        ),
    ]
